@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImF1dGgiOnRydWUsImlkIjoiY2xzMjZ5MXduMDAwMDA4bDE4amQwOWtzdCJ9LCJpYXQiOjE3MDg4ODUyOTQsImV4cCI6MTcwODk3MTY5NH0.C7vgt-zq8Wyd2Ou7dXLs3Eu4JT0zXuXFK3nIynEbqDg


GET http://localhost:8000/ativos
Authorization: Bearer {{token}}

###
GET http://localhost:8000/ativos/jyl4nscqp6393veu6wtcn73j
Authorization: Bearer {{token}}


###
POST http://localhost:8000/ativos
Authorization: Bearer {{token}}
content-type: application/json

{
    "nome": "teste",
    "acronimo": "TSTE1",
	"tipo": "indice"
}

###
PUT http://localhost:8000/ativos
Authorization: Bearer {{token}}
content-type: application/json

{
	"id": "yecfbqf2hw1glgem64w7b8ov",
    "nome": "teste",
    "acronimo": "XSTE2",
	"tipo": "indice"
}


