@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImF1dGgiOnRydWUsImlkIjoiMDE5MGNiNzgtMzQ2YS03MWRmLWI4ZGQtN2ExNjY0ZmE4MDJkIn0sImlhdCI6MTcyNjU5NjUzNCwiZXhwIjoxNzI2NjY4NTM0fQ.T55HDArGAeyCKuwKX-HT8-d4LJIN6iUcQ356Mpd4PDU


GET http://localhost:8000/contas
Authorization: Bearer {{token}}
