@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImF1dGgiOnRydWUsImlkIjoiY2xzMjZ5MXduMDAwMDA4bDE4amQwOWtzdCJ9LCJpYXQiOjE3MTIzNDUyNjMsImV4cCI6MTcxMjQxNzI2M30._AWi0u03kX8trFvakT1IXbnVFrC2-y8jgmq3yOJRgdg


GET http://localhost:8000/contas
Authorization: Bearer {{token}}
