@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImF1dGgiOnRydWUsImlkIjoiMDE5MGNiNzgtMzQ2YS03MWRmLWI4ZGQtN2ExNjY0ZmE4MDJkIn0sImlhdCI6MTczMTQzOTY0NSwiZXhwIjoxNzMxNTExNjQ1fQ.zA4ajHL-NsCsEsLd5gljhr4WdK_NhOKEy0EOp8jVcx0
@path=operacoes
GET http://localhost:8000/{{path}}
Authorization: Bearer {{token}}

###
GET http://localhost:8000/{{path}}/ideo5c6ahm0actaquo5hgr3w
Authorization: Bearer {{token}}

###
GET http://localhost:8000/{{path}}/conta/0190e5d2-a69d-7eed-ad83-69fe31a4c074/range/2024-07-01/2024-07-31
Authorization: Bearer {{token}}


###
POST http://localhost:8000/{{path}}/import
Authorization: Bearer {{token}}
# content-type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
| Content-Disposition: form-data; name="file"; filename="operacoes.csv"
| Content-Type: text/csv
< c:\Users\df90342ps\Desktop\operacoes.csv

------WebKitFormBoundary7MA4YWxkTrZu0gW--


###
POST http://localhost:8000/{{path}}
Authorization: Bearer {{token}}
content-type: application/json

{
	"ativoId": "yecfbqf2hw1glgem64w7b8ov",
	"quantidade": 1,
	"tipo": "compra",
	"precoEntrada": 1000,
	"stopLoss": 900,
	"alvo": 1500,
	"precoSaida": 1500,
	"dataEntrada": "2024-01-19 15:25:00",
	"dataSaida": "2024-01-19 16:25:00",
	"margem": 100,
	"operacaoPerdida": false,
	"operacaoErrada": false
}

###
PUT http://localhost:8000/{{path}}
Authorization: Bearer {{token}}
content-type: application/json

{
	"id": "vyppxjbt2v4l72li2jqiwvdp",
	"ativoId": "yecfbqf2hw1glgem64w7b8ov",
	"quantidade": 1,
	"tipo": "compra",
	"precoEntrada": 1000,
	"stopLoss": 900,
	"alvo": 1500,
	"precoSaida": 1400,
	"dataEntrada": "2024-01-19 9:25:00",
	"dataSaida": "2024-01-21 11:10:00",
	"margem": 100,
	"operacaoPerdida": false,
	"operacaoErrada": false
}
###

DELETE http://localhost:8000/{{path}}/ecw2y2qb7glgtfpves057y1d
Authorization: Bearer {{token}}






