@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjp7ImF1dGgiOnRydWV9LCJpYXQiOjE3MDU5NTI1NDksImV4cCI6MTcwNjAyNDU0OX0.1NIiPpLVVL0ZM7cr7K_zA63nljgM9Lxgkm7kyK8ZK4A
@path = operacoes

GET http://localhost:8000/{{path}}
Authorization: Bearer {{token}}

###
GET http://localhost:8000/{{path}}/ideo5c6ahm0actaquo5hgr3w
Authorization: Bearer {{token}}


###
POST http://localhost:8000/{{path}}
Authorization: Bearer {{token}}
content-type: application/json

{
	"ativoId": "yecfbqf2hw1glgem64w7b8ov",
	"quantidade": 1,
	"tipo": "compra",
	"precoEntrada": 1000,
	"stopLoss": 900,
	"alvo": 1500,
	"precoSaida": 1500,
	"dataEntrada": "2024-01-19 15:25:00",
	"dataSaida": "2024-01-19 16:25:00",
	"margem": 100,
	"operacaoPerdida": false,
	"operacaoErrada": false
}

###
PUT http://localhost:8000/{{path}}
Authorization: Bearer {{token}}
content-type: application/json

{
	"id": "vyppxjbt2v4l72li2jqiwvdp",
	"ativoId": "yecfbqf2hw1glgem64w7b8ov",
	"quantidade": 1,
	"tipo": "compra",
	"precoEntrada": 1000,
	"stopLoss": 900,
	"alvo": 1500,
	"precoSaida": 1400,
	"dataEntrada": "2024-01-19 9:25:00",
	"dataSaida": "2024-01-21 11:10:00",
	"margem": 100,
	"operacaoPerdida": false,
	"operacaoErrada": false
}






