name: Tests
on:
    push:
        branches:
            - main
            - dev
jobs:
  unit-test:
    runs-on: ubuntu-latest
    env:
        NODE_ENV: test
        PORT: 8080
        TEST_TYPE: unit
        DATABASE_URL: "mysql://test:test@localhost:0000/test"
        AUTHENTICATION: true
        SECRET: test
        JWT_EXPIRE: 1h
        NEW_USERS: true
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v4
        - name: Install Dependences
          run: npm ci
        - name: Run Unit Tests
          run: npm run test:unit

  e2e-test:
    needs: [unit-test]
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: e2e_test
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    env:
        NODE_ENV: test
        PORT: 8080
        TEST_TYPE: e2e
        DATABASE_URL: "mysql://root:password@localhost:3306/e2e_test"
        AUTHENTICATION: true
        SECRET: testsecret
        JWT_EXPIRE: 15m
        NEW_USERS: true

    steps:
        - name: Checkout Repository
          uses: actions/checkout@v2
        - name: Setup Node
          uses: actions/setup-node@v4
        - name: Install Dependences
          run: npm ci
        - name: Run Migration
          run: npm run migrate
        - name: Run Tests
          run: npm run test:e2e

